// ------------ CSS ----------------
import "./globals.css";
// ------------ Types ----------------
import { ReactNode } from "react";
// ------------ Fonts ----------------
import { Inter, Roboto_Mono } from "next/font/google"; // Import Google Fonts from Next.js
// ------------ Context ----------------
import { AuthProvider, CartProvider, OrdersProvider } from "../context";
// ------------ Components ----------------
import { Footer, Navbar } from "../components/common";


// Load fonts from Google Fonts
const geistSans = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "CodeSphere",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

// Define props for RootLayout
interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-background-dark-secondary-color`}
      >
        <AuthProvider>
          <CartProvider>
            <OrdersProvider>
              <Navbar />
              {children}
              <Footer />
            </OrdersProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
